server {
    listen 80;
    server_name papadasoftware.com 192.168.100.2;

    root /home/urbano/servidorUbuntu1/frontend/app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://192.168.100.3:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    access_log /home/urbano/servidorUbuntu1/frontend/logs/access.log;
    error_log /home/urbano/servidorUbuntu1/frontend/logs/error.log;
}
